# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Services' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Services
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'

  target 'ServicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Services-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Services-tvOS

  target 'Services-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
