# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Services' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Services
  pod 'Firebase/Core'
  pod 'Firebase/Firestore', '~> 6.2.0'
  pod 'Firebase/Auth', '~> 6.2.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'ServicesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Firestore', '~> 6.2.0'
    pod 'Firebase/Auth', '~> 6.2.0'
  end

end

target 'Services-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Services-tvOS

  target 'Services-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
