//This object contains all of the strings used throughout the entire application.
//Each new defined string must be defined and accessed through this object
export default {
	SomethingWentWrong: 'Something went wrong, please try again later',
	Notifications: 'Notifications',
	Dispatch: 'Dispatch',
	Analytics: 'Analytics',
	Payments: 'Payments',
	Calendar: 'Calendar',
	Home: 'Home',
	Schedule: 'Schedule',
	Settings: 'Settings',
	Employees: 'Employees',
	Customers: 'Customers',
	TimeOffReqs: 'Time Off Request(s)',
	Services: 'Services',
	UnconfirmedReqs: 'Unconfirmed Requests',
	PaymentVerification: 'Payment Verification',
	PaymentVerificationMessage:
		'Help needs some additional information from you in order to accept card payments from customers.',
	OnboardingSucessMessage:
		"Give Stripe some time to verify your details, and we'll notify you once you are able to accept card payments from customers.",
	PaymentsVerifiedSuccss: 'You can now accept card payments from customers!',

	Revenue: 'Revenue',
	TopServices: 'Services',
	CustomerLocations: 'Locations',
	ByMonth: 'by Month',
	ByYear: 'by Year',
	ByCity: 'by City',
	ByState: 'by State',
	ByCountry: 'by Country',
	ByTotalRevenue: 'by Total Revenue',
	ByTotalRequests: 'by Total Requests',
	ByTotalViews: 'by Total Views',
	ByRevenue: 'Revenue ($)',
	ByRequests: 'Requests',
	ByViews: 'Views',
	AverageMonthlyRevenue: 'Average Monthly Revenue: $',
	AverageYearlyRevenue: 'Average Yearly Revenue: $',

	NoDataYet: 'No Data Yet',
	AcceptCardPaymentsWithHelp: 'Accept Card Payments with Help',
	Asterisks: '********',
	DeletePaymentMethod: 'Delete Payment Method',
	AccountName: 'Account Name',
	Bank: 'Bank',
	ExpDate: 'Exp. Date',
	CardNumber: 'Card Number',
	AreYouSureYouWantToDeletePaymentMethod:
		'Are you sure you want to delete your payment method? This cannot be undone.',
	AddPayments: 'Add Payments',
	AndThe: 'and the',
	StripeServicesAgreement: 'Stripe Services Agreement',
	StripeConnectedAccountAgreement: 'Stripe Connected Account Agreement',
	Add: 'Add',
	PleaseAcceptAgreements: 'Please accept the Stripe Agreements.',
	WhereDoYouWantToAcceptPaymentsQuestion: 'Where do you want to accept payments?',
	BankAccount: 'Bank Account',
	DebitCard: 'Debit Card',
	PleaseSelectAWayToAcceptPayments: 'Please select a way to accept payments.',
	InvalidCardType: 'Invalid Card Type',
	InvalidCardTypeMessage: 'You can only accept payments through US Debit Cards and Bank Accounts.',
	AccountNumber: 'Account Number',
	RoutingNumber: 'Routing Number',
	AccountType: 'Account Type',
	AccountHolderName: 'Account Holder Name',
	EnterTheAccountHolderNameDotDotDot: 'Enter the account holder name...',
	EnterTheRoutingNumberDotDotDot: 'Enter the routing number...',
	EnterTheAccountNumberDotDotDot: 'Enter the account number...',
	Company: 'Company',
	BusinessWebsite: 'Business Website',
	EnterYourBusinessNameDotDotDot: 'Enter your legal business name...',
	EnterYourBusinessWebsiteDotDotDot: 'Enter your business website...',
	EnterYourEINDotDotDot: 'Enter your EIN...',
	EIN: 'Employer Identification Number (EIN)',
	Individual: 'Individual',
	EnterStripeInfo: 'Enter Stripe Info',
	EnterStripeInfoMessage:
		'Fill out all necessary fields required by Stripe in order to process card payments.',
	GetStarted: 'Get Started',
	HaveAnAccountQuestion: 'Have an account?',
	LogIn: 'Log In',
	EYB: 'EYB',
	Help: 'Help',
	EnterYourEmail: 'Enter your email...',
	EnterYourPassword: 'Enter your password...',
	IncorrectInfo: 'Incorrect email/password',
	ForgotPassword: 'Forgot Password?',
	ForgotPasswordNoQuestionMark: 'Forgot Password',
	ChooseANewPassword: 'Choose a new password...',
	ResetPassword: 'Reset Password',
	EmailMe: 'Email Me!',
	LinkHasBeenEmailed:
		"If a user with this email exists, a link to reset your password has been sent. Please check your spam/junk folders if you don't see the email.",
	CreateProfile: 'Create Profile',
	AccountNotVerified:
		"Your business has been submitted to the Help staff! Give us up to 24 hours to review your information and then you'll be good to go!",
	Verification: 'Verification',
	SignUp: 'Sign Up',
	Email: 'Email',
	PhoneNumber: 'Phone Number',
	Address: 'Address',
	EnterAnEmail: 'Enter an email...',
	EnterPhoneNumber: 'Enter your phone number...',
	AccountType: 'Account Type',
	Business: 'Business',
	Password: 'Password',
	ChooseAPassword: 'Choose a password...',
	Customer: 'Customer',
	SignUp: 'Sign Up',
	PleaseFillOutAllFields: 'Please fill out all of the above fields',
	PleaseEnterAValidEmail: 'Please enter a valid email',
	NoButtonSelected: 'Please select an account type',
	EmailExists: 'An account with this email already exists. Go back and log into this account',
	ShortPassword: 'Password must be at least 6 characters',
	IAcceptThe: 'I accept the ',
	TermsAndConditions: 'Terms and Conditions',
	CheckTermsAndConditions: 'You must accept the terms and conditions to use Help',
	BusinessPhoneNumberError: 'All businesses are required to enter their phone numbers',
	InvalidPhoneNumberError: 'Please enter a valid 10 digit phone number',
	BusinessSignUp: 'Business Sign Up',
	Next: 'Next',
	Back: 'Back',
	City: 'City',
	Name: 'Name',
	EnterCityDotDotDot: 'Enter city...',
	PleaseEnterName: 'Please enter your name...',
	MyProfile: 'My Profile',
	Blocked: 'Blocked',
	Unblock: 'Unblock',
	UnblockCompany: 'Unblock Company',
	AreYouSureYouWantToUnblock: 'Are you sure you want to unblock ',
	HasBeenUnblocked: 'has been unblocked.',
	History: 'History',
	Privacy: 'Privacy',
	WhenTheyOrder: 'When They Order',
	AfterCompletion: 'After Completion',
	ReportAnIssue: 'Report an Issue',
	Notifications: 'Notifications',
	About: 'About',
	Credits: 'Credits',
	BlockedBusinesses: 'Blocked Businesses',
	LogOut: 'Log Out',
	MarketingMessage: 'Connecting people with service producing businesses',
	PublishedBy: 'Published By',
	HelpLLC: 'Help LLC',
	Contact: 'Contact',
	ContactEmail: 'helpcocontact@gmail.com',
	WhatSeemsToBeTheProblemQuestion: 'What seems to be the problem?',
	DescribeYourIssueHereDotDotDot: 'Describe your issue here...',
	Report: 'Report',
	ThankYouForReporting: 'Thank you for reporting the problem',
	WellFixItRightAway: "We'll fix it right away",
	BusinessName: 'Business Name',
	EnterCompanyNameDotDotDot: 'Enter a company name...',
	BusinessDescription: 'Business Description',
	TellYourCustomersAboutYourselfDotDotDot: 'Tell your customers about yourself...',
	PleaseEnterACompanyName: 'Please enter a company name',
	PleaseEnterADescriptionWithAtLeast150Characters:
		'Please enter a description with at least 150 characters',
	PleaseChooseAValidImage: 'Please choose a valid image',
	CompanyNameTakenPleaseChooseAnotherName: 'This company name is taken, please choose another one',
	Website: 'Website',
	LocationYouServe: 'Location You Serve',
	EnterLocation: 'Enter a location...',
	EnterWebsiteLink: 'Enter a link to your site (Optional)...',
	Ok: 'Ok',
	Location: 'Location',
	WhyWeUseLocation:
		'We collect locations from users to show customers the businesses that are nearest to them. We never share customer locations without their consent. Our intent is to provide the best customer experience.',
	EditCompanyProfile: 'Edit Company Profile',
	PlusSign: '+',
	CreateYourFirstProductNowExclamation: 'Create your first product now!',
	Create: 'Create',
	FinishCreatingYourProfile: 'Finish Creating Your Profile',
	FinishCreatingYourProfileMessage:
		"Your business doesn't have all the info customers need! Go complete your profile.",
	CreateService: 'Create Service',
	ServiceTitle: 'Service Title',
	EnterTitleForService: 'Enter a title for your service...',
	EditServiceImage: 'Edit Service Image',
	ServiceDescription: 'Service Description',
	EnterDescriptionForCustomersDotDotDot: 'Enter a description for customers to see...',
	PricingAndPayment: 'Pricing & Payment',
	PricingType: 'Pricing Type',
	Hour: 'Hour',
	PleaseSelectAPaymentMethod: 'Please select a way for customers to pay you.',
	PleaseSelectPaymentTime: 'Please select when your customers will pay you.',
	Pricing: 'Pricing',
	HowMuchWillYouChargeDotDotDot: 'How much will you charge...',
	PleaseCompleteAllTheFields: 'Please complete all the fields',
	PleaseAddAnImage: 'Please add an image',
	Per: 'Per',
	Range: 'Range',
	DollarSign: '$',
	per: 'per',
	Fixed: 'Fixed',
	ServiceDeleted: 'This service has been deleted',
	Min: 'Min',
	Max: 'Max',
	to: 'to',
	PleaseEnterADescriptionWithAtLeast50Characters:
		'Please enter a description with at least 150 characters.',
	DeleteService: 'Delete Service',
	AreYouSureDeleteService:
		'Are you sure you want to delete this service? This action cannot be undone.',
	TheServiceHasInProgressRequests:
		'The service currently has requests that are in progress. Please complete those requests before deleting the service.',
	TheServiceHasBeenDeleted: 'The service has been deleted.',
	Schedule: 'Schedule',
	PickADate: 'Pick a Date',
	PickATime: 'Pick a Time',
	FinishRequesting: 'Finish Request',
	AreYouSureYouWantToRequest: 'Are you sure you want to request ',
	isAvailableBetween: 'is available between',
	and: 'and',
	PleaseSelectATimeInWhichTheBusinessIsAvailable:
		'Please select a time in which the business is available.',
	PleaseSelectATimeForYourService: 'Please select a time for your service.',
	AreYouSureYouWantToOverwriteOldRequest:
		'Are you sure you want to overwrite your request for this service?',
	SaveRequest: 'Save Request',
	Save: 'Save',
	TheServiceRequestHasBeenSaved: 'Your request has been saved',
	PleaseSelectADayForYourService: 'Please select a day for your service.',
	RequestedBy: 'Requested By',
	BusinessHours: 'Business Hours',
	WorkingHours: 'Working Hours',
	ToTimeMustBeAfterFromTime: "The 'To' time needs to be after the 'from' time.",
	Monday: 'Mon',
	Tuesday: 'Tue',
	Wednesday: 'Wed',
	Thursday: 'Thu',
	Friday: 'Fri',
	Saturday: 'Sat',
	Sunday: 'Sun',
	BusinessUpdated: 'Business Updated',
	BusinessUpdatedMessage: 'Your business information has been updated.',
	InfoFromCustomersQuestion:
		'What information do you need from customers to complete this services?',
	CustomQuestions: 'Custom Questions',
	CustomQuestionsDescription:
		'What information do you need from the customer to complete the service?',
	AddQuestion: 'Add Question',
	Question: 'Question',
	WorkerManagement: 'Worker Management',
	EnterAQuestionForCustomerHere: 'Enter a question for the customer to answer here...',
	WhatIsYourEmailAddressQuestion: 'What is your email address?',
	WhatIsYourAddressQuestion: 'What is your address?',
	WhatIsYourPhoneNumberQuestion: 'What is your phone number?',
	EmptyQuestion: 'Please fill out all empty questions or remove them.',
	ServiceDuration: 'Service Duration',
	Hours: 'Hrs',
	Minutes: 'Mins',
	AddNewService: 'Add New Service',
	AmountOfServicesAtATime: 'How many requests can you do at a time?',
	Requests: 'Requests',
	SimultaneousRequests: '# of Simultaneous Requests',
	SimultaneousRequestsMessage:
		'How many employees could your company send out to complete this request at the same time?',
	HowWillCustomersPay: 'How will customers pay for this service?',
	Cash: 'Cash',
	Card: 'Card',
	CreditDebitCard: 'Credit/Debit Card',
	SetUpPayment: 'Set Up Payments',
	HowWillYourCustomersPayYou: 'How will your customers pay you?',
	WhenDoYouWantYourCustomersToPayYou: 'When do you want your customers to pay you?',
	PaymentTime: 'Payment Time',
	PaymentMethod: 'Payment Method',
	PaymentsMustBeSetupBeforeAcceptingCardPayments:
		'Payments must be set up before accepting card transactions.',
	Billing: 'Billing',
	HowMuchWasTheCustomerChargedForTheService: 'How much was the customer charged for the service?',
	ExampleBilledAmount: '0.00',
	PleaseConfirmThatThisIsThePriceTheCustomerShouldBeChargedForThisService:
		'Please confirm that this is the price the customer should be charged for this service.',
	ThePriceForThisServiceWas: 'The price for this service was ',
	PleaseEnterAmountUnitsSoPriceCanBeCalculated:
		'Please enter the amount of units there were for this request so the final price can be calculated.',
	Zero: '0',
	PleaseEnterAmountOf: 'Please enter the amount of ',
	ThereWereForThisRequestSoThatTheFinalPriceCanBeCalculated:
		' there were for this request so that the final price can be calculated.',
	ParanthesesS: '(s)',
	EditCompany: 'Edit Company',
	EditName: 'Edit Name',
	EditDescription: 'Edit Description',
	Done: 'Done',
	Service: 'Service',
	EditService: 'Edit Service',
	Cancel: 'Cancel',
	ViewRequests: 'View Requests',
	EditTitle: 'Edit Title',
	EditDescription: 'Edit Description',
	EditPrice: 'Edit Price',
	CustomerInfo: 'Customer Info',
	Questions: 'Questions',
	Edit: 'Edit',
	ServiceHistory: 'Service History',
	NoHistoryForThisServiceYet: 'No history for this service yet',
	CompletedOn: 'Completed on',
	BilledColon: 'Billed: $',
	CustomerRequest: 'Customer Request',
	Delete: 'Delete',
	Message: 'Message',
	RequestedOn: 'Requested On',
	Complete: 'Complete',
	CustomerAnswers: 'Customer Answers',
	ScheduledOn: 'Scheduled on',
	ScheduledAt: 'Scheduled at',
	at: 'at',
	AreYouSureDeleteRequest: 'Are you sure you want to delete this request?',
	DeleteRequest: 'Delete Request',
	RequestDeleted: 'Request Deleted',
	RequestHasBeenDeleted: 'The request has been deleted',
	RequestCompleted: 'Request Completed',
	RequestHasBeenCompleted: 'The request has been completed.',
	CompleteRequest: 'Complete Request',
	AreYouSureCompleteRequest: 'Are you sure you want to complete this request?',
	BilledAmount: 'Billed Amount',
	Date: 'Date',
	Time: 'Time',
	Employee: 'Employee',
	Customer: 'Customer',
	Payment: 'Payment',
	Address: 'Address',
	PhoneNumber: 'Phone Number',
	Email: 'Email',
	AssignEmployees: 'Assign Employees',
	Assign: 'Assign',
	Assigned: 'Assigned',
	EmployeeAssigned: 'Employee Assigned',
	EmployeeAssignedMessage: 'You assigned NAME to the following service:',
	EmployeeAssignedCalenderMessage: "This request has been added to NAME's calender!",
	Close: 'Close',
	AdditionalInformation: 'Additional Information',
	PaymentType: 'Payment Type',
	Price: 'Price',
	RequestID: 'Request ID',
	NoCurrentRequestsForThisService: 'No Current Requests For This Service',
	CurrentRequests: 'Current Requests',
	OfferedBy: 'Offered by',
	NoCurrentServices: 'There are no current services available to request. Check back soon!',
	Featured: 'Featured',
	FeaturedServices: 'Featured Services',
	LeaveAReview: 'Leave A Review',
	BusinessName: 'Business Name',
	Submit: 'Submit',
	Skip: 'Skip',
	LeaveAReviewDotDotDot: 'Leave a review...',
	PleaseGiveAStarRatingAlongWithReview: 'Please give a star rating along with your review.',
	FeaturedCategories: 'Featured Categories',
	ServiceRequested: 'Service Requested',
	CancelRequest: 'Cancel Request',
	RequestService: 'Request Service',
	AreYouSureRequestService: 'Are you sure you want to request this service?',
	Yes: 'Yes',
	CompanyServices: 'Company Services',
	MoreByThisBusiness: 'More by this business',
	ReadMore: 'Read More',
	ReadLess: 'Read Less',
	CustomerReviews: 'Customer Reviews',
	ServiceDeleted: 'The business no longer sells this service.',
	CompanyBlocked: 'Company Blocked',
	CompanyHasBeenBlocked: 'The company has been blocked',
	ViewRequest: 'View Request',
	AnswerHereDotDotDot: 'Answer here...',
	PleaseFillOutAllQuestions: 'Please fill out all of the questions.',
	TheServiceHasBeenRequested: 'The service has been requested.',
	OrderHistory: 'Order History',
	InProgress: 'In Progress',
	Completed: 'Completed',
	NoRequestsYet: "You haven't requested anything yet! Go check out our services by going to Home",
	RequestHasBeenCancelled: 'Your request has been cancelled',
	AreYouSureCancelRequest: 'Are you sure you want to cancel your request for this service?',
	OrderAgain: 'Order Again',
	Home: 'Home',
	Chats: 'Chats',
	Settings: 'Settings',
	LogOut: 'Log Out',
	Credits: 'Credits',
	Categories: 'Categories',
	CompanyProfile: 'Company Profile',
	Block: 'Block',
	CompanyReported: 'Company Reported',
	AreYouSureYouWantToBlock: 'Are you sure your want to block',
	CompanyHasBeenReported:
		'This company has been reported. Help staff will take a look. Thank you for your patience.',
	NoMessagesYet: 'No messages yet',
	Today: 'Today',
	NewRequest: 'New Request',
	YouHaveNewRequestFor: 'You have a new request for ',
	YourRequestFor: 'Your request for',
	HasBeenRemovedBecause: 'has been removed because',
	RequestRemoved: 'Request Removed',
	NoLongerSellsThisService: 'no longer sells this service.',
	RequestCancelled: 'Request Cancelled',
	HasCancelledTheirRequestFor: 'has cancelled their request for',
	HasUpdatedTheirRequestFor: 'has updated their request for',
	RequestUpdated: 'Request Updated',
	PrivacyPolicy: 'Privacy Policy',
	WhatAreYouLookingForQuestion: 'What are you looking for?',
	SearchIn: 'Search in',
	SearchCategoriesDotDotDot: 'Search categories...',
	SelectPhoto: 'Select a Photo',
	TakePhotoDotDotDot: 'Take Photo...',
	ChooseFromLibraryDotDotDot: 'Choose from Library...',
	Whoops: 'Whoops',
	DotDotDot: '...',
	Success: 'Success',
	Ok: 'Ok',
	NoConnection: 'Something went wrong. Check your internet connection & try again',
	UpdateAvailable: 'Update Available',
	UpdateAvailableMessage: 'There is a new update available for Help! Go download it now!',
	Restart: 'Restart',
	AppWillRestart: 'Help will now restart to install the update.',
	UnderMaintenance: 'Under Maintenance',
	AppIsUnderMaintenance:
		'Help is currently under scheduled maintenance. It should be back up soon.',
	Confirmation: 'Confirmation',
	CompletionDate: 'Completion Date',
	Recipient: 'Recipient',
	Total: 'Total',
	Signature: 'Signature',
	Clear: 'Clear',
	SendEmailConfirmation: 'Send email confirmation',
	RecipientEmail: 'Recipient Email',
	PleaseAddACustomerSignature: 'Please add a customer signature.',
	PleaseAddARecipientEmail: 'Please add a recipient email.',
	Confirm: 'Confirm',
	Employee: 'Employee',
	ConfirmPassword: 'Confirm Password',
	PleaseEnterPhoneNumber: 'Please enter a valid phone number...',
	Join: 'Join',
	Dashboard: 'Dashboard',
	AddNewService: 'Add New Service',
	Edit: 'Edit',
	Approve: 'Approve',
	Deny: 'Deny',
	ProfileDefaultBusinessName: 'Business',
	ProfileEditCompanyInfo: 'Edit Company Info',
	ProfileBusinessSchedule: 'Business Schedule',
	ProfilePassword: 'Change Password',
	ProfileTermsPrivacyCredits: 'Terms/Privacy/Credits',
	ProfileLogout: 'Log Out',
	ConfirmRequest: 'Confirm Request',
	Loading: 'Loading...',
	OldPassword: 'Current Password',
	NewPassword: 'New Password',
	ConfirmNewPassword: 'Confirm New Password',
	PasswordChanged: 'Password Changed',
	Error: 'Error',
	PasswordsDoNotMatch: 'The new passwords do not match',
	WeakPassword: 'Your new password is not strong enough',
	IncorrectPassword: 'Your current password is incorrect',
	BusinessName: 'Business Name',
	BusinessWebsite: 'Business Website',
	BusinessPhoneNumber: 'Business Phone Number',
	BusinessLocation: 'Business Location',
	BusinessDescription: 'Business Description',
	SaveChanges: 'Save Changes',
	ChangesSaved: 'Changes Saved',
	To: 'to',
	AddNewService: 'Add New Service',
	ServiceTitlePlaceholder: 'Enter a title for your service...',
	DescriptionPlaceholder: 'Enter a description for your customers to see...',
	PricingAndPayment: 'Pricing & Payment',
	ExampleHourPlaceholder: 'E.g Hour',
	NumberPlaceholder: '#',
	Employees: 'Employees',
	TotalBalance: 'Total USD Balance',
	ViewDetails: 'View Details',
	All: 'All',
	ViewMore: 'View More',
	RefundRequest: 'Refund Request',
	Succeeded: 'Succeeded',
	Amount: 'Amount',
	Customer: 'Customer',
	Date: 'Date',
	PaymentSuccessful: 'Payment Successful',
	RefundRequested: 'Refund Requested',
	AccountBalance: 'Account Balance',
	PendingFunds: 'Funds On The Way To Your Bank',
	CurrentFunds: 'Current Funds',
	TotalBalance2: 'Total Balance',
	RecentTransactions: 'Recent Transactions',
	ServiceInfo: 'Service Info',
	Requests: 'Requests',
	RequestsHistory: 'Request History',
	UnconfirmedRequests: 'Unconfirmed Requests',
	Description: 'Description',
	DaysOffered: 'Days Offered',
	ServiceDuration: 'Service Duration',
	PricingAndPayment: 'Pricing & Payment Type',
	EditServiceImage: 'Edit Service Image',
	Ratings: 'Ratings',
	RequestTimeOff: 'Request Time Off',
	AllDay: 'All Day',
	Comments: 'Comments',
	SelectDate: 'Select Date',
	SelectDateAndTime: 'Select Date & Time',
	From: 'From',
	To: 'To',
	SendRequest: 'Send request',
	OnMyWay: 'On My Way',
	Start: 'Start',
	Done: 'Done',
	Finish: 'Finish',
	EnrouteText: 'Send en-route text?',
	StartJob: 'Start this job?',
	FinishJob: 'Finish this job?',
	Cance: 'Cancel',
	Send: 'Send',
	ContinueToPayment: 'Continue to Payment',
	JobCompleted: 'Job completed.\nYour employer has\nbeen notified.',
	TransactionHistory: 'Transaction History',
	PayoutHistory: 'Payout History',
	BAN: 'Bank Account Number',
	PayoutSchedule: 'Payout Schedule',
	DPayout: 'Daily Payout',
	WPayout: 'Weekly Payout',
	MPayout: 'Monthly Payout',
	YPayout: 'Yearly Payout',
	Change: 'Change',
	Error: 'Error',
	InvalidBAN: 'Please enter a valid bank account number',
	TermsPrivacyCredits: 'Terms/Privacy/Credits',
	TotalBalance: 'Total USD Balance',
	ViewDetails: 'View Details',
	All: 'All',
	ViewMore: 'View More',
	RefundRequest: 'Refund Request',
	Succeeded: 'Succeeded',
	Amount: 'Amount',
	Customer: 'Customer',
	Date: 'Date',
	PaymentSuccessful: 'Payment Successful',
	RefundRequested: 'Refund Requested',
	AccountBalance: 'Account Balance',
	PendingFunds: 'Funds On The Way To Your Bank',
	CurrentFunds: 'Current Funds',
	TotalBalance2: 'Total Balance',
	RecentTransactions: 'Recent Transactions',
	ServiceInfo: 'Service Info',
	Requests: 'Requests',
	RequestsHistory: 'Request History',
	UnconfirmedRequests: 'Unconfirmed Requests',
	Description: 'Description',
	DaysOffered: 'Days Offered',
	ServiceDuration: 'Service Duration',
	PricingAndPayment: 'Pricing & Payment Type',
	EditServiceImage: 'Edit Service Image',
	Ratings: 'Ratings',
	RequestTimeOff: 'Request Time Off',
	AllDay: 'All Day',
	Comments: 'Comments',
	SelectDate: 'Select Date',
	SelectDateAndTime: 'Select Date & Time',
	From: 'From',
	To: 'To',
	SendRequest: 'Send request',
	OnMyWay: 'On My Way',
	Start: 'Start',
	Done: 'Done',
	Finish: 'Finish',
	EnrouteText: 'Send en-route text?',
	StartJob: 'Start this job?',
	FinishJob: 'Finish this job?',
	Cance: 'Cancel',
	Send: 'Send',
	ContinueToPayment: 'Continue to Payment',
	JobCompleted: 'Job completed.\nYour employer has\nbeen notified.',
	TransactionHistory: 'Transaction History',
	PayoutHistory: 'Payout History',
	BAN: 'Bank Account Number',
	RN: 'Routing Number',
	PayoutSchedule: 'Payout Schedule',
	DPayout: 'Daily Payout',
	WPayout: 'Weekly Payout',
	MPayout: 'Monthly Payout',
	YPayout: 'Yearly Payout',
	Change: 'Change',
	Error: 'Error',
	InvalidBAN: 'Please enter a valid bank account number',
	TermsPrivacyCredits: 'Terms/Privacy/Credits',
	ViewWeek:"View Week",
	ViewMonth:"View Month",
	NoRequests:'No requests',
	nextHour: "In the next hour",
	nextSixHours: "In the next 6 hours",
	nextDay: "In the next 24 hours",
	nextWeek: "In the next 7 days",
	nextMonth: "In the next 30 days",
	TOpending: "Time Off Req Pending",
	TOrequest: "Time Off Req",
	StartTime: "Start Time",
	EndTime: "End Time",
	AddRequest: "Add Request",
	PaymentInformation: "Payment Information",
};
