//This is where all of the strings will be for the website
export default {
	HelpForBusiness: 'Help for Business',
	LogIn: 'Log In',
	SignUp: 'Sign Up',
	ContactUs: 'Contact Us',
	HelpEmail: 'helpcocontact@gmail.com',
	HelpPhoneNumber: '+1 (425) 229-9185',
	HelpAddress: '13543 NE 200th ST',
	HelpCity: 'Woodinville, WA 98072',
	JoinHelpFamily: 'Join the Help Family',
	Legal: 'Legal',
	PrivacyPolicy: 'Privacy Policy',
	TermsAndConditions: 'Terms & Conditions',
	Credits: 'Credits',
	Copyright: '2020- Help',
	Help: 'Help',
	EnhanceYourBusiness: 'Enhance Your Business',
	ConnectWithCustomers: 'Connect with Customers',
	ConnectWithCustomersMessage:
		'Allow customers to browse and request your services through a website or an app.',
	SmartScheduling: 'Smart Scheduling',
	SmartSchedulingMessage:
		'Automate your schedule by having customers schedule a time that works for them, and works for you.',
	AdvancedAnalytics: 'Advanced Analytics',
	AdvancedAnalyticsMessage:
		'Analyze your business over time and make data-driven decisions based on things like Monthly Revenue, Top Services, and Customer Locations.',
	CentralizedPayments: 'Centralized Payments',
	CentralizedPaymentsMessage:
		'Allow customers to pay through the secure Help platform however they want, and accept it all in one place.',
	EmployeeManagement: 'Employee Management',
	EmployeeManagementMessage:
		"If you are a business owner, manage how your employees complete requests through Help's employee management features.",
	StartSellingToday: 'Start Selling Today',
	StartSellingTodayMessage:
		'Connect with your customers and take your business to the next level today.',
	PercentageMessage: '5% per successful transaction',
	per: 'per',
	fixed: 'fixed',
	Email: 'Email',
	PhoneNumber: 'Phone Number',
	Address: 'Address',
	WhatIsYourEmailAddressQuestion: 'What is your email address?',
	WhatIsYourAddressQuestion: 'What is your address?',
	WhatIsYourPhoneNumberQuestion: 'What is your phone number?',
	Sunday: 'Sun',
	Monday: 'Mon',
	Tuesday: 'Tue',
	Wednesday: 'Wed',
	Thursday: 'Thu',
	Friday: 'Fri',
	Saturday: 'Sat',
	AdjustJobHeader: 'Adjust Job',
	RequestFromHeader: 'Request From:',
	AssignedEmployeesHeader: 'Assigned Employees:',
	NotesHeader: 'Notes',
	ShowAllNotesSubHeader: 'Show All Notes',
	CalendarHeader: 'Calendar',
	Day: 'Day',
	Week: 'Week',
	Month: 'Month',
	Year: 'Year',
	TwelveAM: '12 AM',
	OneAM: '1 AM',
	TwoAM: '2 AM',
	ThreeAM: '3 AM',
	FourAM: '4 AM',
	FiveAM: '5 AM',
	SixAm: '6 AM',
	SevenAM: '7 AM',
	EightAM: '8 AM',
	NineAM: '9 AM',
	TenAM: '10 AM',
	ElevenAM: '11 AM',
	TwelvePM: '12 PM',
	OnePM: '1 PM',
	TwoPM: '2 PM', 
	ThreePM: '3 PM',
	FourPM: '4 PM',
	FivePM: '5 PM',
	SixPM: '6 PM',
	SevenPM: '7 PM',
	EightPM: '8 PM',
	NinePM: '9 PM',
	TenPM: '10 PM',
	ElevenPM: '11 PM'
};