//This is where all of the strings will be for the website
export default {
	HelpForBusiness: 'Help for Business',
	LogIn: 'Log In',
	SignUp: 'Sign Up',
	ContactUs: 'Contact Us',
	HelpEmail: 'helpcocontact@gmail.com',
	HelpPhoneNumber: '+1 (425) 229-9185',
	HelpAddress: '13543 NE 200th ST',
	HelpCity: 'Woodinville, WA 98072',
	JoinHelpFamily: 'Join the Help Family',
	Legal: 'Legal',
	PrivacyPolicy: 'Privacy Policy',
	TermsAndConditions: 'Terms & Conditions',
	Credits: 'Credits',
	Copyright: '2020- Help',
	Help: 'Help',
	EnhanceYourBusiness: 'Enhance Your Business',
	ConnectWithCustomers: 'Connect with Customers',
	ConnectWithCustomersMessage:
		'Allow customers to browse and request your services through a website or an app.',
	SmartScheduling: 'Smart Scheduling',
	SmartSchedulingMessage:
		'Automate your schedule by having customers schedule a time that works for them, and works for you.',
	Total: 'Total',
	Analytics: 'Analytics',
	Dashboard: 'Dashboard',
	Calendar: 'Calendar',
	CancelRequest: 'Cancel Request',
	CancelRequestMessage: 'Are you sure you want to cancel this request?',
	CompleteRequest: 'Complete Request',
	Dispatch: 'Dispatch',
	Profile: 'Profile',
	AdvancedAnalytics: 'Advanced Analytics',
	AdvancedAnalyticsMessage:
		'Analyze your business over time and make data-driven decisions based on things like Monthly Revenue, Top Services, and Customer Locations.',
	CentralizedPayments: 'Centralized Payments',
	CentralizedPaymentsMessage:
		'Allow customers to pay through the secure Help platform however they want, and accept it all in one place.',
	EmployeeManagement: 'Employee Management',
	EmployeeManagementMessage:
		"If you are a business owner, manage how your employees complete requests through Help's employee management features.",
	StartSellingToday: 'Start Selling Today',
	StartSellingTodayMessage:
		'Connect with your customers and take your business to the next level today.',
	PercentageMessage: '5% per successful transaction',
	per: 'per',
	fixed: 'fixed',
	Email: 'Email',
	PhoneNumber: 'Phone Number',
	Address: 'Address',
	WhatIsYourEmailAddressQuestion: 'What is your email address?',
	WhatIsYourAddressQuestion: 'What is your address?',
	WhatIsYourPhoneNumberQuestion: 'What is your phone number?',
	ContactUs: 'Contact Us',
	LetsLaunch: "Let's launch your business into success!",
	ContactInformation: 'Contact Information',
	LetsGrow: "Let's Grow Your Business",
	ReadyToStartWorkingTogether:
		"Ready to start working together? Have a general question? We're only an email away.",
	LetUsHelp: 'Let us Help your business thrive.',
	WorkTogether: "Let's work together",
	OurServices: 'Our Services',
	WhatWeDoBest: 'What We Do Best',
	SmartScheduling: 'Smart Scheduling',
	SmartSchedulingText:
		'Automate your schedule by having customers schedule a time that works for them and for you.',
	AdvancedAnalyticsText:
		'Analyze your business over time and make data-driven decisions based on things like Monthly Revenue, Top Services, and Customer Locations.',
	PaymentsText:
		'Allow customers to pay through the secure Help platform however they want and accept it all in one place.',
	EmployeeText:
		'Manage how your employees complete requests through Help’s employee management features.',
	ConnectText: 'Connect with your customers and take your business to the next level today.',
	StartSelling: 'Start Selling',
	Today: 'Today',
	HelpForBusiness: 'Help for Business',
	LogIn: 'Log In',
	LogOut: 'Log Out',
	SignUp: 'Sign Up',
	ContactUs: 'Contact Us',
	HelpEmail: 'helpcocontact@gmail.com',
	HelpPhoneNumber: '+1 (425) 229-9185',
	HelpAddress: '13543 NE 200th ST',
	HelpCity: 'Woodinville, WA 98072',
	JoinHelpFamily: 'Join the Help Family',
	Legal: 'Legal',
	PrivacyPolicy: 'Privacy Policy',
	TermsAndConditions: 'Terms & Conditions',
	Credits: 'Credits',
	Copyright: '2020- Help',
	Help: 'Help',
	EnhanceYourBusiness: 'Enhance Your Business',
	ConnectWithCustomers: 'Connect with Customers',
	ConnectWithCustomersMessage:
		'Allow customers to browse and request your services through a website or an app.',
	SmartScheduling: 'Smart Scheduling',
	SmartSchedulingMessage:
		'Automate your schedule by having customers schedule a time that works for them, and works for you.',
	AdvancedAnalytics: 'Advanced Analytics',
	AdvancedAnalyticsMessage:
		'Analyze your business over time and make data-driven decisions based on things like Monthly Revenue, Top Services, and Customer Locations.',
	CentralizedPayments: 'Centralized Payments',
	CentralizedPaymentsMessage:
		'Allow customers to pay through the secure Help platform however they want, and accept it all in one place.',
	Payment: 'Payment',
	QuestionResponses: 'Question Responses:',
	EmployeeManagement: 'Employee Management',
	EmployeeManagementMessage:
		"If you are a business owner, manage how your employees complete requests through Help's employee management features.",
	StartSellingToday: 'Start Selling Today',
	StartSellingTodayMessage:
		'Connect with your customers and take your business to the next level today.',
	PercentageMessage: '5% per successful transaction',
	Fixed: 'Fixed',
	Email: 'Email',
	PhoneNumber: 'Phone Number',
	Address: 'Address',
	Website: 'Website',
	BusinessName: 'Business Name',
	BusinessDescription: 'Business Description...',
	WhatIsYourEmailAddressQuestion: 'What is your email address?',
	WhatIsYourAddressQuestion: 'What is your address?',
	WhatIsYourPhoneNumberQuestion: 'What is your phone number?',
	Sunday: 'Sun',
	Monday: 'Mon',
	Tuesday: 'Tue',
	Wednesday: 'Wed',
	Thursday: 'Thu',
	Friday: 'Fri',
	Saturday: 'Sat',
	MarkasComplete: 'Mark as Complete',
	RequestFromHeader: 'Request From:',
	RequestFrom: 'Request From',
	Assign: 'Assign',
	Assigned: 'Assigned',
	AssignedEmployees: 'Assigned Employees',
	NotesHeader: 'Notes',
	ShowAllNotesSubHeader: 'Show All Notes',
	CalendarHeader: 'Calendar',
	Day: 'Day',
	Week: 'Week',
	Month: 'Month',
	Year: 'Year',
	TwelveAM: '12 AM',
	OneAM: '1 AM',
	TwoAM: '2 AM',
	ThreeAM: '3 AM',
	FourAM: '4 AM',
	FiveAM: '5 AM',
	SixAm: '6 AM',
	SevenAM: '7 AM',
	EightAM: '8 AM',
	NineAM: '9 AM',
	TenAM: '10 AM',
	ElevenAM: '11 AM',
	TwelvePM: '12 PM',
	OnePM: '1 PM',
	TwoPM: '2 PM',
	ThreePM: '3 PM',
	FourPM: '4 PM',
	FivePM: '5 PM',
	SixPM: '6 PM',
	SevenPM: '7 PM',
	EightPM: '8 PM',
	NinePM: '9 PM',
	TenPM: '10 PM',
	ElevenPM: '11 PM',
	ContactUs: 'Contact Us',
	LetsLaunch: "Let's launch your business into success!",
	ContactInformation: 'Contact Information',
	LetsGrow: "Let's Grow Your Business",
	ReadyToStartWorkingTogether:
		"Ready to start working together? Have a general question? We're only an email away.",
	AddNewService: 'Add New Service',
	PricingAndPayment: 'Pricing & Payment',
	CustomerInfo: 'Customer Info',
	OneNumber: '1',
	TwoNumber: '2',
	ThreeNumber: '3',
	StepOne: 'Step 1',
	StepTwo: 'Step 2',
	ServiceTitle: 'Service Title',
	EnterTitleForService: 'Enter a title for your service...',
	ServiceDescription: 'Service Description',
	EnterServiceDescription: 'Enter a description for customers to see...',
	ServiceDuration: 'Service Duration',
	Hrs: 'Hrs',
	Mins: 'Mins',
	Hours: 'Hours',
	Minutes: 'Minutes',
	EditServiceImage: 'Edit Service Image',
	EditService: 'Edit Service',
	NextWithArrow: 'Next >',
	Next: 'Next',
	BusinessWebsite: 'Business Website (Optional)',
	ConfirmPassword: 'Confirm Password',
	Error: 'Error',
	Close: 'Close',
	SignUpFieldError:
		'Make sure you fill out all required information correctly and have at least 150 characters in the description.',
	to: 'to',
	AgreeToPolicies: "I agree to Help's Terms & Conditions and its Privacy Policy",
	BackWithArrow: '< Back',
	Create: 'Create',
	PricingType: 'Pricing Type',
	DollarSign: '$',
	Per: 'Per',
	per: 'per',
	Hour: 'Hour',
	PaymentType: 'Payment Type:',
	Cash: 'Cash',
	CreditDebitCard: 'Credit/Debit Card',
	WhenDoYouWantYourCustomersToPayYou: 'When do you want your customers to pay you?',
	HowWillYourCustomersPayYou: 'How will your customers pay you?',
	WhenTheyOrder: 'When They Order',
	AfterCompletion: 'After Completion',
	CustomQuestions: 'Custom Questions',
	WhatInformationDoYouNeed:
		'What information do you need from the customer to complete this service?',
	AddQuestion: 'Add Question',
	EnterQuestionForCustomer: 'Enter a question for the customer here...',
	QuestionNumber: 'Question #',
	PleaseCompleteAllFields: 'Please complete all the fields.',
	Whoops: 'Whoops',
	PleaseAddAnImage: 'Please add an image.',
	DescriptionError: 'Your description must be at least 150 characters.',
	Analytics: 'Analytics',
	MonthlyRevenue: 'Monthly Revenue',
	SortBy: 'Sort By',
	LoadingChart: 'Loading Chart',
	RevenueDollarSign: 'Revenue ($)',
	TopServices: 'Top Services',
	Requests: 'Requests',
	Views: 'Views',
	Revenue: 'Revenue',
	TopLocations: 'Top Locations',
	City: 'City',
	State: 'State',
	Country: 'Country',
	Home: 'Home',
	Payments: 'Payments',
	GoToMap: 'Go to Map',
	EmailAddress: 'Email Address',
	BusinessNameOptional: 'Business Name',
	Message: 'Message',
	SubmitCapital: 'SUBMIT',
	BestDays: 'Best Days',
	ViewMore: 'View More',
	ViewAll: 'View All',
	Cancel: 'Cancel',
	EmailMe: 'Email Me',
	ForgotPasswordQuestion: 'Forgot Password?',
	Ok: 'Ok',
	EmailSentExclamation: 'Email Sent!',
	Close: 'Close',
	GoToSignUp: 'Go to Sign Up',
	ErrorSendingEmail: 'Error Sending Email',
	ErrorSigningUp:
		'There was an error signing you up. Make sure you fill out all required information, then try again.',
	AgreeToPolicies: "I agree to Help's Terms and Conditions and Privacy Policy",
	BusinessSchedule: 'Business Schedule',
	SortByMonth: 'Sort By Month',
	SortByYear: 'Sort By Year',
	SortByCity: 'Sort By City',
	SortByState: 'Sort By State',
	SortByCountry: 'Sort By Country',
	SortByRequests: 'Sort By Requests',
	SortByRevenue: 'Sort By Revenue',
	SortByViews: 'Sort By Views',
	BusinessAddress: 'Business Address',
	businessPhoneNumber: 'Business Phone Number',
	ChangePassword: 'Change Password',
	OldPassword: 'Old Password',
	NewPassword: 'New Password',
	ConfirmNewPassword: 'Confirm New Password',
	CompanyInfo: 'Company Info',
	Business: 'Business',
	Password: 'Password',
	CompletedColon: 'Completed:',
	TotalColonDollar: 'Total: $',
	PastServicesRequests: 'Past Services Requests',
	CurrentRequests: 'Current Requests',
	RequestsHistory: 'Requests History',
	UnconfirmedRequests: 'Unconfirmed Requests',
	ConfirmedRequests: 'Confirmed Requests',
	EditProfilePicture: 'Edit Profile Picture',
	SaveChanges: 'Save Changes',
	ConfirmRequest: 'Confirm Request',
	RequestAddedToCalendar: 'This request has been added to your Calendar!',
	CustomerNotified: 'The customer has been notified that you will be able to fulfill this request!',
	RequestConfirmed: 'Request Confirmed',
	Success: 'Success',
	YourPasswordHasBeenChanged: 'Your password has been changed.',
	PasswordLengthMessage: 'Password must be at least 6 characters.',
	PasswordsMustMatchMessage: "Passwords don't match.",
	IncorrectPasswordMessage: 'Your password is incorrect.',
	YourInfoHasBeenUpdated: 'Your information has been updated',
	BusinessInformation: 'Business Information',
	EmailFormattingErrorMessage: 'Please enter a valid email format',
	TimeErrorMessage: 'Your ending hours must be after your starting hours.',
	RememberMe: 'Remember Me',
	EditProfile: 'Edit Profile',
	Card: 'Card',
	Cash: 'Cash',
	View: 'View',
	EditService: 'Edit Service',
	ServiceDescription: 'Service Description',
	Rating: 'Rating',
	DaysOffered: 'Days Offered',
	ViewAll: 'View All',
	Total: 'Total:',
	GreetingMessageFirstPart:  'Hi, follow this link to sign up with Help and join the',
	GreetingMessageSecondPart: 'using this code:', 
	InviteEmployees: 'Invite Employee(s)',
	Dispatch: 'Dispatch', 
	JoinCodeForEmployees: 'Join Code For Your Employees',
	ShareTheCode: 'Share this 5-digit code with your employees',
	TimeOffRequests: 'Time Off Request(s)',
	Approve: 'Approve',
	Deny: 'Deny',
	Request:"Request",
	SeeAllServices: "See All Services",
	FeaturedServices:"Featured Services",
	OfferedBy:"Offered By:",
	Questions:"Questions",
	Time:"Time",
	To:"To",
	Repeat: "Repeat",
	FirstName:'First Name',
	LastName: 'Last Name',
	CardNumber:'Card Number',
	Expiration: 'Exp',
	CCV: 'CCV',
	Loading:"Loading...",
};
